### ISSUE TITLE
Layout issues on Notebook Displays

### ISSUE THREAD

**Issue by Daniel-CS-Team** [dfirtrack/dfirtrack#129]
![DFIRTrack-LowRes](https://user-images.githubusercontent.com/66005732/128832972-477b00a9-5bc7-49c7-9cd6-882e88ffafc3.png)

When using DFIRTrack on a display with a smaller resolution, the layout is broken (see screenshot).
This happens already when using notebook displays, so we are not talking about Smartphones...
As we would also need to update inormation inthe field, where we only have our notebook arround, it should be usable with any resolution.

**Comment by stuhli** [comment]
Hi, sorry to hear that.

We use DFIRTrack very often directly on the notebook (smallest display 13 inches) and have not had the problem so far. As a workaround it should help to reduce the zoom a little in the browser? Since we don't have a dedicated frontend developer, I don't see a solution for this in the medium term, since it works on the whole.

Which display size, which browser and which zoom factor are we talking about?

**Comment by Daniel-CS-Team** [comment]
Yes, reducing the zoom-factor helps. The problem appears on a MacBook 16 inch with 3072 × 1920 in Firefox with 120% zoom-level. But in the team, it could be reproduced in different Browser and Notebook combinations. 
I guess the CSS is not optmized for different Window-Sizes. Unfrotuantely, I am Incident Responder and not Web-Developer, so besides of reporting the isssue, there is not much I can do to help.

**Comment by stuhli** [comment]
Yes, most of the people involved in the project are also incident responders and only limited (backend) developers. Frontend even less.

I think that you can solve this with the Bootstrap used, but I know too little about it. I'll leave the issue open anyway. Maybe there is someone who wants to deal with it?

**Comment by stuhli** [comment]
This was fixed by #140
