### ISSUE TITLE
Add case-title for system overview and export

### ISSUE THREAD

**Issue by ghost** [dfirtrack/dfirtrack#39]
Hi,

would be nice to see the referenced cases in system overview table as also in export formats.

Filtering on those kind of data would be nice too.

Regards,
Hendrik

**Comment by stuhli** [comment]
Hi,

cases in tables might be editable after implementing #26 but I'm not sure at the moment. Because this is a many-to-many relationship this could become slightly confusing.

Anyway, I'm not sure yet how to handle cases in the future. At the moment I'm not happy with the implemention of cases at all (system --> many-to-many, entry --> one-to-many). The idea was to mark systems in APT cases compromised with seperate malware (e. g. crimeware or similar stuff) but this was never used. We use more often tags for this. And I'm not sure how meaningful it is to mark single (timeline) entries as there is no possibility to evaluate this.

The question to the community is: who would use cases and in what context? And what would make it differ from https://github.com/TheHive-Project/TheHive or https://github.com/certsocietegenerale/FIR for example? Because me intention is not to rebuild a case management framework.

How would you expect to work the cases in the export functions? Can you give an example please? My plan is to make the exports more customizable by the user in future.

Regards
stuhli

**Comment by stuhli** [comment]
Since there is no more activity in this issue and the request should be obsolete due to the many new features since then, I will close here.
