### ISSUE TITLE
Errors with initial setup

### ISSUE THREAD

**Issue by ghost** [dfirtrack/dfirtrack#51]
Hello,
I've been following the minimal setup instructions on the wiki with a clean Ubuntu 16.04 build, however have run into a few errors.
It looks like you need to add a step to do a:
`python3 manage.py migrate`
as the tables aren't there to run the server properly.

However, when I do try and browse to the webserver once it's running, I don't see any of the static content - I've checked that JavaScript is enabled. Any ideas?

**Comment by stuhli** [comment]
Hi,
yeah thanks. Obviously I forgot the `migrate` command. I recently fixed the wiki.

Regarding the static content:
Do you run DFIRTrack using the development server? I quess yes because you were following the minimal setup. I checked `dfirtrack.settings`. If you use the development server you either have to provide a `dfirtrack.local_settings` (which is automatically imported because of `from .local_settings import ALLOWED_HOSTS, DATABASES, DEBUG` or you have to change in `dfirtrack.settings` to `DEBUG = True` (should be the fastest way).
Please try this. It this solves your problem I will leave a hint in the wiki.

**Comment by ghost** [comment]
Thanks for the quick response!

I was just using a clean Ubuntu Server 16.04 and followed the steps on that wiki page - what do you mean the development server?

**Comment by ghost** [comment]
Ah, I see what you mean. I did just change `DEBUG = True` and it worked. Thanks!

**Comment by stuhli** [comment]
I added some explanation on it in the wiki.
