### ISSUE TITLE
Artifact creator

### ISSUE THREAD

**Issue by Lequant-0815** [dfirtrack/dfirtrack#92]
Create an artifact and assign this to more than one system.
I think it would be nice if it were possible to assign one artifact for more than one system. e.g. a file request.

**Comment by stuhli** [comment]
System - Artifact is a 1:N relationship. Means, one system may have multiple artifacts, but an artifact always belongs to exactly one system. Each artifact is an instantiated object of the class artifacts. If you want to collect the same artifact (e.g. a certain file) from several systems, each file is a separate artifact that belongs to exactly one system.

The behavior described above would rather be a kind of meta-artifact and contradicts the object idea of how artifacts work in DFIRTrack. Otherwise it would not be possible to track the status of each artifact (e.g. how far the acquisition is). We do not plan to adapt the data model in this direction.

With _Workflows_, it is relatively easy to create multiple (standardized) artifacts per system (i.e. rather the opposite of what you want to achieve). With workflows in conjunction with the _Creator_, this even works for multiple systems at the same time when creating the systems. With the current PR regarding workflows (which is still open) there will be the possibility to create artifacts in the course of the _Modificator_. This is probably in the direction of the desired behavior. However, an unintentional change of the system status would be the consequence.

So I assume what is needed here is an **_Artifact Creator_**? So a simple possibility to create a similar artifact for several systems (each as a separate object instance)...
